import json
import os
from pathlib import Path

APPDATA_DIR = Path(os.getenv('LOCALAPPDATA')) / 'Zapret Launcher'
CONFIG_FILE = APPDATA_DIR / 'config.json'

class Languages:
    LANGUAGES = {
        'Russian': 'Русский',
        'English': 'English'
    }
    
    TRANSLATIONS = {
        'Russian': {
            'main_title': 'Главная',
            'main_desc': 'Управление подключением и мониторинг состояния',
            'status': 'Статус:',
            'status_ready': 'Готов к работе',
            'status_connected': 'Подключено',
            'mode': 'Режим:',
            'mode_not_selected': 'Не выбран',
            'stats_session': 'Статистика сессии',
            'stats_time': 'время работы',
            'stats_speed': 'Скорость:',
            'stats_rtt': 'RTT:',
            'stats_rtt_ms': 'ms',
            'button_connect': 'ПОДКЛЮЧИТЬСЯ',
            'button_disconnect': 'ОТКЛЮЧИТЬСЯ',
            
            'service_title': 'Сервис',
            'service_desc': 'Дополнительные сервисы и функции программы',
            'service_filters': 'Фильтры',
            'service_game_filter': 'Game Filter',
            'service_ipset_filter': 'IPSet Filter',
            'service_updates': 'Обновление',
            'service_update_launcher': 'Обновить лаунчер',
            'service_update_zapret': 'Обновить Zapret',
            
            'lists_title': 'Редактор',
            'lists_desc': 'Редактирование списков для обхода блокировок',
            'lists_general': 'General листы',
            'lists_google': 'Google листы',
            'lists_edit': 'Изменить',
            'lists_open_folder': 'Расположение ZL',
            
            'diagnostic_title': 'Диагностика',
            'diagnostic_desc': 'Проверка состояния компонентов и диагностика сети',
            'diagnostic_zapret': 'Zapret',
            'diagnostic_zapret_status': 'Проверить статус',
            'diagnostic_zapret_logs': 'Логи winws.exe',
            'diagnostic_zapret_restart': 'Перезапустить',
            'diagnostic_zapret_auto': 'Авто-подбор',
            'diagnostic_tgproxy': 'TGProxy',
            'diagnostic_tgproxy_status': 'Проверить статус',
            'diagnostic_tgproxy_restart': 'Перезапустить',
            'diagnostic_system': 'Система',
            'diagnostic_system_appdata': 'Папка AppData',
            'diagnostic_system_autostart': 'Автозапуск',
            'diagnostic_system_optimize': 'Оптимизация сети',
            'diagnostic_system_dns_find': 'Найти DNS',
            'diagnostic_system_dns_flush': 'Очистить DNS',
            'diagnostic_system_restore': 'Сбросить настройки',
            'diagnostic_general': 'Общая диагностика',
            'diagnostic_general_full': 'Полная проверка',
            'diagnostic_general_report': 'Сохранить отчет',
            'diagnostic_general_integrity': 'Проверка файлов',
            'diagnostic_general_clear': 'Очистить кеш',
            'diagnostic_results': 'Результаты диагностики',
            
            'shutdown_title': 'Сбои интернета',
            'shutdown_desc': 'Проверка доступности популярных сервисов',
            'shutdown_refresh': 'Обновить',
            'shutdown_active': 'Активен',
            'shutdown_error': 'Ошибка',
            'shutdown_update_info': 'Данные обновляются в течение 60 секунд',
            'shutdown_last_update': 'Последнее обновление:',
            'shutdown_service': 'Сервис',
            'shutdown_status': 'Статус',
            'shutdown_source': 'Источник',
            'shutdown_available': 'Доступен',
            'shutdown_redirect': 'Редирект',
            'shutdown_timeout': 'Таймаут',
            'shutdown_limited': 'Доступ ограничен',
            'shutdown_not_found': 'Страница не найдена',
            'shutdown_server_error': 'Ошибка сервера',
            'shutdown_updating': 'Обновление...',
            'shutdown_code': 'Код',
            'shutdown_no_connection': 'Нет соединения',
            'shutdown_unknown': 'Неизвестно',
            
            'traffic_title': 'Трафик',
            'traffic_desc': 'Мониторинг сетевого трафика по процессам',
            'traffic_process': 'Процесс',
            'traffic_speed': 'Скорость',
            'traffic_vpn': 'VPN',
            'traffic_direct': 'Прямой',
            'traffic_connections': 'Соед.',
            'traffic_host': 'Хост',
            'traffic_total': 'Всего',
            'traffic_no_connections': 'Нет активных соединений',
            'error_traffic_collection': 'Ошибка сбора трафика',
            
            'settings_title': 'Настройки',
            'settings_desc': 'Настройка интерфейса и параметров работы',
            'settings_interface': 'Обновление интерфейса',
            'settings_interval_fast': 'Быстро',
            'settings_interval_5': '5 секунд',
            'settings_interval_10': '10 секунд',
            'settings_interval_30': '30 секунд',
            'settings_interval_60': '60 секунд',
            'settings_interval_off': 'Не обновлять',
            'settings_current': 'Текущие настройки',
            'settings_current_interval': 'Обновление интерфейса:',
            'settings_interval_fast_text': 'быстро',
            'settings_interval_off_text': 'отключено',
            'settings_language': 'Язык / Language',
            'settings_language_desc': 'Выберите язык интерфейса',
            'settings_theme': 'Тема оформления',
            'settings_theme_desc': 'Выберите тему интерфейса',
            'settings_current_tg_secret': 'Текущий секрет:',
            
            'mode_standard': 'Стандартный',
            'mode_standard_desc': 'Обход блокировок через Zapret',
            'mode_tgproxy': 'Telegram Proxy',
            'mode_tgproxy_desc': 'Ускорение работы Telegram',
            'mode_zapret_tgproxy': 'Совместный',
            'mode_zapret_tgproxy_desc': 'Zapret и Telegram Proxy',
            'mode_game': 'Игровой',
            'mode_game_desc': 'Производительность для игр',
            'mode_select': 'Выберите режим запуска',
            'mode_select_button': 'Выбрать',
            'mode_cancel': 'Отмена',
            
            'notification_copied': 'Ссылка скопирована в буфер обмена',
            'notification_interval_fast': 'Обновление интерфейса: быстро',
            'notification_interval_5': 'Обновление интерфейса: 5 секунд',
            'notification_interval_10': 'Обновление интерфейса: 10 секунд',
            'notification_interval_30': 'Обновление интерфейса: 30 секунд',
            'notification_interval_60': 'Обновление интерфейса: 60 секунд',
            'notification_interval_off': 'Обновление интерфейса: отключено',
            
            'dialog_exit': 'Выход',
            'dialog_exit_message': 'Активное подключение будет разорвано.\n\nВы действительно хотите закрыть программу?',
            'dialog_no_connection': 'Программа не может работать без прав администратора',
            'dialog_admin_required': 'Права администратора',
            'dialog_admin_message': 'Программа требует прав администратора для работы\n\nЗапустить от имени администратора?',
            'restart_manual_title': 'Требуется перезапуск',
            'restart_manual_message': 'Настройки сохранены.\n\nПожалуйста, перезапустите программу вручную для применения изменений',
            
            'tg_instruction_title': 'Настройка Telegram',
            'tg_instruction_subtitle': 'Для использования прокси выполните следующие шаги:',
            'tg_generate_secret': 'Сгенерировать секрет-ключ',
            'tg_copy_secret': 'Скопировать секрет-ключ',
            'tg_step1': 'Откройте Telegram и перейдите в',
            'tg_step1_desc': 'Настройки - Продвинутые настройки',
            'tg_step2': 'В разделе «Тип соединения» выберите:',
            'tg_step2_desc': 'Использовать собственный прокси',
            'tg_step3': 'Заполните поля прокси:',
            'tg_type': 'Тип: MTProto',
            'tg_host': 'Хост: 127.0.0.1',
            'tg_port': 'Порт: 1080',
            'tg_secret': 'Secret: (Генерируется автоматически)',
            'tg_copy_link': 'Скопировать ссылку подключения',
            'tg_copied': 'Скопировано',
            'tg_dont_show': 'Больше не показывать',
            'tg_start': 'Запустить',
            
            'update_launcher_title': 'Обновление Zapret Launcher',
            'update_launcher_available': 'Доступна новая версия лаунчера!',
            'update_launcher_current': 'Текущая версия:',
            'update_launcher_new': 'Новая версия:',
            'update_launcher_question': 'Перейти на страницу загрузки?',
            'update_launcher_latest': 'У вас установлена последняя версия лаунчера',
            'update_zapret_title': 'Обновление Zapret',
            'update_zapret_available': 'Доступна новая версия Zapret!',
            'update_zapret_current': 'Текущая версия:',
            'update_zapret_new': 'Новая версия:',
            'update_zapret_question': 'Хотите обновить? (Ваши пользовательские списки будут сохранены)',
            'update_zapret_latest': 'У вас установлена последняя версия Zapret',
            'update_zapret_success': 'Zapret успешно обновлен до версии',
            'update_zapret_failed': 'Не удалось обновить Zapret',
            'update_go': 'Перейти',
            
            'error_update_check': 'Не удалось проверить обновления',
            'error_rate_limit': 'Превышен лимит запросов к GitHub API.\nПожалуйста, попробуйте позже.',
            'error_no_strategies': 'Нет доступных стратегий Zapret',
            'error_select_strategy': 'Выберите стратегию',
            'error_zapret_folder': 'Папка с Zapret не найдена!',
            'error_tgproxy_start': 'Не удалось запустить Telegram Proxy',
            'error_tgproxy_timeout': 'Таймаут запуска',
            'error_admin_required': 'Требуются права администратора!',
            'error_strategy_not_found': 'Стратегия не найдена:',
            'error_winws_not_found': 'Стратегия запущена, но winws.exe не обнаружен',
            'error_secret_not_found': 'Секрет-ключ не найден',
            'error_secret_not_generate': 'Секрет-ключ не сгенерирован',
            'error_telegram_proxy_start': 'Сначала запустите Telegram Proxy режим',
            'error_startup': 'Ошибка запуска',
            'error_icon_not_found': 'Иконка не найдена',
            'error_unknown_command': 'Неизвестная команда',
            'error_autostart': 'Ошибка настройки автозапуска',
            'error_no_connection': 'Ошибка',
            'error_occurred': 'Произошла ошибка',

            'tg_secret_required_message': 'Для работы Telegram Proxy требуется секрет-ключ.\n\nСгенерировать новый секрет и продолжить?',
            'tg_secret_updated': 'Секрет-ключ обновлен',
            'tg_secret_new': 'Новый секрет:',
            'tg_paste_instruction': 'Вставьте её в Telegram для подключения.',
            'tg_proxy_restarted': 'Прокси перезапущен с новым секретом.',
                        
            'status_connecting': 'Запуск...',
            'status_disconnecting': 'Отключение...',
            'status_connected_tg': 'Подключено: Telegram Proxy',
            'status_connected_zapret': 'Подключено: Стратегия',
            'status_starting_tg': 'Запуск Telegram Proxy...',
            'status_starting': 'Запуск...',
            'status_error': 'Ошибка запуска',
            'status_searching_dns': 'Поиск DNS...',
            'status_updating_zapret': 'Обновление Zapret...',
            'status_strategy_started': 'Запущена стратегия:',
            'status_enabled': 'включен',
            'status_disabled': 'выключен',
            
            'autostart_enabled': 'Программа будет запускаться при старте Windows',
            'autostart_disabled': 'Автозапуск отключен',
            'autostart_error': 'Не удалось изменить настройки автозапуска',
            
            'dns_server_not_responding': 'DNS сервер не отвечает',
            'dns_no_adapters': 'Не найдены активные сетевые адаптеры',
            'dns_set_failed': 'Не удалось установить DNS ни на один адаптер',
            'dns_adapters_count': 'адаптер(ов)',
            'dns_chimney_disabled': 'TCP Chimney отключен',
            'dns_chimney_error': 'Не удалось отключить TCP Chimney',
            'dns_rss_disabled': 'RSS отключен',
            'dns_rss_error': 'Не удалось отключить RSS',
            'dns_autotuning_set': 'TCP автонастройка установлена в normal',
            'dns_autotuning_error': 'Не удалось настроить TCP автонастройку',
            'dns_window_size_increased': 'TCP Window Size увеличен',
            'dns_1323_enabled': 'TCP 1323 опции включены',
            'dns_registry_error': 'Ошибка реестра',
            'dns_errors': 'Ошибки',
            'dns_autotuning_restored': 'TCP автонастройка восстановлена (normal)',
            'dns_chimney_enabled': 'TCP Chimney включен',
            'dns_rss_enabled': 'RSS включен',
            'dns_restored_for': 'DNS восстановлен для',
            'dns_set_for_adapter': 'DNS установлен для адаптера',
            'dns_optimize': 'Сетевые параметры оптимизированы!\n\nПерезагрузите компьютер для применения изменений',
            'dns_set': 'Установлен DNS:',
            'dns_primary': 'Primary:',
            'dns_secondary': 'Secondary:',
            'dns_latency': 'Задержка:',
            'dns_optimize_network': 'ОПТИМИЗАЦИЯ СЕТИ',
            'dns_configuring_tcp': 'Настройка TCP параметров...',
            'dns_optimize_complete': 'Оптимизация завершена',
            'dns_optimize_success': 'Сетевые параметры оптимизированы!\n\nПерезагрузите компьютер для применения изменений',
            'dns_searching_best': 'ПОИСК ЛУЧШЕГО DNS СЕРВЕРА',
            'dns_testing_servers': 'Тестирование DNS серверов...',
            'dns_best_set': 'Установлен подходящий DNS:',
            'dns_set_success': 'Успех',
            'dns_for_adapter': 'для адаптера',
            'dns_select_adapter': 'Выбор сетевого адаптера',
            'dns_flushing': 'Очистка DNS кеша...',
            'dns_flush_success': 'DNS кеш очищен',
            'dns_restoring_defaults': 'Восстановление стандартных настроек сети...',
            'dns_restore_success': 'Стандартные настройки восстановлены',
            
            'editor_title': 'Редактирование',
            'editor_save': 'Сохранить',
            'editor_cancel': 'Отмена',
            'editor_success': 'Файл успешно сохранен!',
            'editor_error_load': 'Не удалось загрузить файл',
            'editor_error_save': 'Не удалось сохранить файл',
            
            'menu_open': 'Открыть лаунчер',
            'menu_connect': 'Подключиться',
            'menu_disconnect': 'Отключиться',
            'menu_check_updates': 'Проверить обновления',
            'menu_exit': 'Выход',
            
            'button_start': 'Запустить',
            'button_apply': 'Применить',
            'button_close': 'Закрыть',
            'button_restart': 'Перезапустить',
            
            'select_strategy': 'Выбор стратегии Zapret',
            'available_strategies': 'Доступные стратегии:',
            'selected': 'Выбрано',
            
            'category_providers': 'Провайдеры',
            'category_messengers': 'Мессенджеры',
            'category_social': 'Соцсети',
            'category_search': 'Поисковики',
            'category_games': 'Игры',
            'category_banks': 'Банки',
            'category_gov': 'Госуслуги',
            'category_other': 'Прочее',
            
            'success': 'Успех',
            
            'diagnostic_auto_strategy': 'АВТОМАТИЧЕСКИЙ ПОДБОР СТРАТЕГИИ',
            'diagnostic_testing': 'Тестируем:',
            'diagnostic_failed_to_start': 'Не удалось запустить:',
            'diagnostic_started': 'Запущена',
            'diagnostic_result': 'Результат:',
            'diagnostic_best_strategy': 'Подходящая стратегия:',
            'diagnostic_restoring_connection': 'Восстанавливаем подключение...',
            'diagnostic_no_working_strategy': 'Не найдена работающая стратегия',
            'diagnostic_zapret_running': 'Zapret запущен',
            'diagnostic_zapret_not_running': 'Zapret не запущен',
            'diagnostic_searching_winws': 'Поиск процессов winws.exe...',
            'diagnostic_started_at': 'запущен:',
            'diagnostic_strategy': 'Стратегия',
            'diagnostic_winws_not_found': 'Процессы winws.exe не найдены',
            'diagnostic_restarting_zapret': 'Перезапуск Zapret...',
            'diagnostic_checking_zapret': 'Проверка статуса Zapret...',
            'diagnostic_zapret_restarted': 'Zapret перезапущен',
            'diagnostic_zapret_not_started': 'Zapret не был запущен',
            'diagnostic_checking_tgproxy': 'Проверка статуса TGProxy...',
            'diagnostic_tgproxy_running': 'TGProxy запущен',
            'diagnostic_tgproxy_not_running': 'TGProxy не запущен',
            'diagnostic_restarting_tgproxy': 'Перезапуск TGProxy...',
            'diagnostic_tgproxy_restarted': 'TGProxy перезапущен',
            'diagnostic_tgproxy_not_started': 'TGProxy не был запущен',
            'diagnostic_opening_folder': 'Открытие папки:',
            'diagnostic_full_diagnostic': 'ПОЛНАЯ ДИАГНОСТИКА',
            'diagnostic_launcher_version': 'Версия лаунчера:',
            'diagnostic_current_dns': 'Текущие DNS серверы:',
            'diagnostic_complete': 'Диагностика завершена',
            'diagnostic_report_saved': 'Отчет сохранен:',
            'diagnostic_clearing_cache': 'Очистка кеша...',
            'diagnostic_checking': 'Проверка...',
            'diagnostic_available': 'ДОСТУПЕН',
            'diagnostic_not_available': 'НЕ ДОСТУПЕН',
            'diagnostic_dns_error': 'DNS ОШИБКА - сайт не найден',
            'diagnostic_timeout': 'ТАЙМАУТ - сайт не отвечает',
            'diagnostic_enter_url': 'Введите URL сайта:',
            'diagnostic_not_determined': 'не определяется',
            'diagnostic_all_ok': 'Все файлы в порядке',
            'diagnostic_check_error': 'ошибка проверки',
            'diagnostic_file_integrity': 'ПРОВЕРКА ЦЕЛОСТНОСТИ ФАЙЛОВ',
            'diagnostic_check_site': 'Проверка сайта',
        },
        
        'English': {
            'main_title': 'Home',
            'main_desc': 'Connection management and monitoring',
            'status': 'Status:',
            'status_ready': 'Ready',
            'status_connected': 'Connected',
            'mode': 'Mode:',
            'mode_not_selected': 'Not selected',
            'stats_session': 'Session statistics',
            'stats_time': 'uptime',
            'stats_speed': 'Speed:',
            'stats_rtt': 'RTT:',
            'stats_rtt_ms': 'ms',
            'button_connect': 'CONNECT',
            'button_disconnect': 'DISCONNECT',
            
            'service_title': 'Service',
            'service_desc': 'Additional services and functions',
            'service_filters': 'Filters',
            'service_game_filter': 'Game Filter',
            'service_ipset_filter': 'IPSet Filter',
            'service_updates': 'Updates',
            'service_update_launcher': 'Update launcher',
            'service_update_zapret': 'Update Zapret',
            
            'lists_title': 'Editor',
            'lists_desc': 'Edit lists for bypassing blocks',
            'lists_general': 'General lists',
            'lists_google': 'Google lists',
            'lists_edit': 'Edit',
            'lists_open_folder': 'ZL Location',
            
            'diagnostic_title': 'Diagnostic',
            'diagnostic_desc': 'Component status check and network diagnostics',
            'diagnostic_zapret': 'Zapret',
            'diagnostic_zapret_status': 'Check status',
            'diagnostic_zapret_logs': 'winws.exe logs',
            'diagnostic_zapret_restart': 'Restart',
            'diagnostic_zapret_auto': 'Auto-select',
            'diagnostic_tgproxy': 'TGProxy',
            'diagnostic_tgproxy_status': 'Check status',
            'diagnostic_tgproxy_restart': 'Restart',
            'diagnostic_system': 'System',
            'diagnostic_system_appdata': 'AppData folder',
            'diagnostic_system_autostart': 'Autostart',
            'diagnostic_system_optimize': 'Optimize network',
            'diagnostic_system_dns_find': 'Find DNS',
            'diagnostic_system_dns_flush': 'Flush DNS',
            'diagnostic_system_restore': 'Reset settings',
            'diagnostic_general': 'General diagnostic',
            'diagnostic_general_full': 'Full check',
            'diagnostic_general_report': 'Save report',
            'diagnostic_general_integrity': 'Check files',
            'diagnostic_general_clear': 'Clear cache',
            'diagnostic_results': 'Diagnostic results',
            
            'shutdown_title': 'Internet outages',
            'shutdown_desc': 'Check availability of popular services',
            'shutdown_refresh': 'Refresh',
            'shutdown_active': 'Active',
            'shutdown_error': 'Error',
            'shutdown_update_info': 'Data updates within 60 seconds',
            'shutdown_last_update': 'Last update:',
            'shutdown_service': 'Service',
            'shutdown_status': 'Status',
            'shutdown_source': 'Source',
            'shutdown_available': 'Available',
            'shutdown_redirect': 'Redirect',
            'shutdown_timeout': 'Timeout',
            'shutdown_limited': 'Access limited',
            'shutdown_not_found': 'Page not found',
            'shutdown_server_error': 'Server error',
            'shutdown_updating': 'Updating...',
            'shutdown_code': 'Code',
            'shutdown_no_connection': 'No connection',
            'shutdown_unknown': 'Unknown',
            
            'traffic_title': 'Traffic',
            'traffic_desc': 'Network traffic monitoring by process',
            'traffic_process': 'Process',
            'traffic_speed': 'Speed',
            'traffic_vpn': 'VPN',
            'traffic_direct': 'Direct',
            'traffic_connections': 'Conn.',
            'traffic_host': 'Host',
            'traffic_total': 'Total',
            'traffic_no_connections': 'No active connections',
            'error_traffic_collection': 'Traffic collection error',
            
            'settings_title': 'Settings',
            'settings_desc': 'Interface and operation settings',
            'settings_interface': 'Interface refresh',
            'settings_interval_fast': 'Fast',
            'settings_interval_5': '5 seconds',
            'settings_interval_10': '10 seconds',
            'settings_interval_30': '30 seconds',
            'settings_interval_60': '60 seconds',
            'settings_interval_off': 'Disabled',
            'settings_current': 'Current settings',
            'settings_current_interval': 'Interface refresh:',
            'settings_interval_fast_text': 'fast',
            'settings_interval_off_text': 'disabled',
            'settings_language': 'Language',
            'settings_language_desc': 'Select interface language',
            'settings_theme': 'Theme',
            'settings_theme_desc': 'Select interface theme',
            'settings_current_tg_secret': 'Current secret:',
            
            'mode_standard': 'Standard',
            'mode_standard_desc': 'Bypass blocks via Zapret',
            'mode_tgproxy': 'Telegram Proxy',
            'mode_tgproxy_desc': 'Telegram acceleration',
            'mode_zapret_tgproxy': 'Combined',
            'mode_zapret_tgproxy_desc': 'Zapret and Telegram Proxy',
            'mode_game': 'Gaming',
            'mode_game_desc': 'Performance for games',
            'mode_select': 'Select launch mode',
            'mode_select_button': 'Select',
            'mode_cancel': 'Cancel',
            
            'notification_copied': 'Link copied to clipboard',
            'notification_interval_fast': 'Interface refresh: fast',
            'notification_interval_5': 'Interface refresh: 5 seconds',
            'notification_interval_10': 'Interface refresh: 10 seconds',
            'notification_interval_30': 'Interface refresh: 30 seconds',
            'notification_interval_60': 'Interface refresh: 60 seconds',
            'notification_interval_off': 'Interface refresh: disabled',
            
            'dialog_exit': 'Exit',
            'dialog_exit_message': 'Active connection will be terminated.\n\nDo you really want to close the program?',
            'dialog_no_connection': 'The program cannot run without administrator rights',
            'dialog_admin_required': 'Administrator rights',
            'dialog_admin_message': 'The program requires administrator rights to run\n\nRun as administrator?',
            'restart_manual_title': 'Restart Required',
            'restart_manual_message': 'Settings have been saved.\n\nPlease restart the program manually to apply the changes',
            
            'tg_instruction_title': 'Telegram Setup',
            'tg_instruction_subtitle': 'To use the proxy, follow these steps:',
            'tg_generate_secret': 'Generate secret-key',
            'tg_copy_secret': 'Copy the secret-key',
            'tg_step1': 'Open Telegram and go to',
            'tg_step1_desc': 'Settings - Advanced Settings',
            'tg_step2': 'In the "Connection Type" section select:',
            'tg_step2_desc': 'Use custom proxy',
            'tg_step3': 'Fill in the proxy fields:',
            'tg_type': 'Type: MTProto',
            'tg_host': 'Host: 127.0.0.1',
            'tg_port': 'Port: 1080',
            'tg_secret': 'Secret: (auto-generated)',
            'tg_copy_link': 'Copy connection link',
            'tg_copied': 'Copied',
            'tg_dont_show': 'Don\'t show again',
            'tg_start': 'Start',
            
            'update_launcher_title': 'Zapret Launcher Update',
            'update_launcher_available': 'New launcher version available!',
            'update_launcher_current': 'Current version:',
            'update_launcher_new': 'New version:',
            'update_launcher_question': 'Go to download page?',
            'update_launcher_latest': 'You have the latest launcher version',
            'update_zapret_title': 'Zapret Update',
            'update_zapret_available': 'New Zapret version available!',
            'update_zapret_current': 'Current version:',
            'update_zapret_new': 'New version:',
            'update_zapret_question': 'Update? (Your custom lists will be preserved)',
            'update_zapret_latest': 'You have the latest Zapret version',
            'update_zapret_success': 'Zapret successfully updated to version',
            'update_zapret_failed': 'Failed to update Zapret',
            'update_go': 'Go',
            
            'error_update_check': 'Failed to check for updates',
            'error_rate_limit': 'GitHub API rate limit exceeded.\nPlease try again later.',
            'error_no_strategies': 'No Zapret strategies available',
            'error_select_strategy': 'Select a strategy',
            'error_zapret_folder': 'Zapret folder not found!',
            'error_tgproxy_start': 'Failed to start Telegram Proxy',
            'error_tgproxy_timeout': 'Startup timeout',
            'error_admin_required': 'Administrator rights required!',
            'error_strategy_not_found': 'Strategy not found:',
            'error_winws_not_found': 'Strategy started but winws.exe not detected',
            'error_secret_not_found': 'Secret-key not found',
            'error_secret_not_generate': 'The secret key was not generated',
            'error_telegram_proxy_start': 'First, launch Telegram Proxy mode',
            'error_startup': 'Startup error',
            'error_unknown_command': 'Unknown command',
            'error_autostart': 'Autostart configuration error',
            'error_no_connection': 'Error',
            'error_occurred': 'Error occurred',

            'tg_secret_required_message': 'A secret-key is required for Telegram Proxy to work.\n\nGenerate a new secret and continue?',
            'tg_secret_updated': 'Secret-key updated',
            'tg_secret_new': 'New secret:',
            'tg_paste_instruction': 'Paste it into Telegram to connect.',
            'tg_proxy_restarted': 'Proxy restarted with new secret.',
                        
            'status_connecting': 'Starting...',
            'status_disconnecting': 'Disconnecting...',
            'status_connected_tg': 'Connected: Telegram Proxy',
            'status_connected_zapret': 'Connected: Strategy',
            'status_starting_tg': 'Starting Telegram Proxy...',
            'status_starting': 'Starting...',
            'status_error': 'Startup error',
            'status_searching_dns': 'Searching DNS...',
            'status_updating_zapret': 'Updating Zapret...',
            'status_strategy_started': 'Strategy started:',
            'status_enabled': 'enabled',
            'status_disabled': 'disabled',
            
            'autostart_enabled': 'Program will start with Windows',
            'autostart_disabled': 'Autostart disabled',
            'autostart_error': 'Failed to change autostart settings',

            'dns_server_not_responding': 'DNS server not responding',
            'dns_no_adapters': 'No active network adapters found',
            'dns_set_failed': 'Failed to set DNS on any adapter',
            'dns_adapters_count': 'adapter(s)',
            'dns_chimney_disabled': 'TCP Chimney disabled',
            'dns_chimney_error': 'Failed to disable TCP Chimney',
            'dns_rss_disabled': 'RSS disabled',
            'dns_rss_error': 'Failed to disable RSS',
            'dns_autotuning_set': 'TCP autotuning set to normal',
            'dns_autotuning_error': 'Failed to configure TCP autotuning',
            'dns_window_size_increased': 'TCP Window Size increased',
            'dns_1323_enabled': 'TCP 1323 options enabled',
            'dns_registry_error': 'Registry error',
            'dns_errors': 'Errors',
            'dns_autotuning_restored': 'TCP autotuning restored (normal)',
            'dns_chimney_enabled': 'TCP Chimney enabled',
            'dns_rss_enabled': 'RSS enabled',
            'dns_restored_for': 'DNS restored for',
            'dns_set_for_adapter': 'DNS set for adapter',
            'dns_optimize': 'Network parameters optimized!\n\nRestart your computer to apply changes',
            'dns_set': 'DNS set:',
            'dns_primary': 'Primary:',
            'dns_secondary': 'Secondary:',
            'dns_latency': 'Latency:',
            'dns_optimize_network': 'NETWORK OPTIMIZATION',
            'dns_configuring_tcp': 'Configuring TCP parameters...',
            'dns_optimize_complete': 'Optimization complete',
            'dns_optimize_success': 'Network parameters optimized!\n\nRestart your computer to apply changes',
            'dns_searching_best': 'SEARCHING FOR BEST DNS SERVER',
            'dns_testing_servers': 'Testing DNS servers...',
            'dns_best_set': 'Best DNS set:',
            'dns_set_success': 'Success',
            'dns_for_adapter': 'for adapter',
            'dns_select_adapter': 'Select network adapter',
            'dns_flushing': 'Flushing DNS cache...',
            'dns_flush_success': 'DNS cache flushed',
            'dns_restoring_defaults': 'Restoring network defaults...',
            'dns_restore_success': 'Network defaults restored',
            
            'editor_title': 'Editing',
            'editor_save': 'Save',
            'editor_cancel': 'Cancel',
            'editor_success': 'File saved successfully!',
            'editor_error_load': 'Failed to load file',
            'editor_error_save': 'Failed to save file',
            
            'menu_open': 'Open launcher',
            'menu_connect': 'Connect',
            'menu_disconnect': 'Disconnect',
            'menu_check_updates': 'Check for updates',
            'menu_exit': 'Exit',
            
            'button_start': 'Start',
            'button_apply': 'Apply',
            'button_close': 'Close',
            'button_restart': 'Restart',
            
            'select_strategy': 'Select Zapret strategy',
            'available_strategies': 'Available strategies:',
            'selected': 'Selected',
            
            'category_providers': 'Providers',
            'category_messengers': 'Messengers',
            'category_social': 'Social networks',
            'category_search': 'Search engines',
            'category_games': 'Games',
            'category_banks': 'Banks',
            'category_gov': 'Government',
            'category_other': 'Other',
            
            'tooltip_settings': 'Click for settings',
            'success': 'Success',
            
            'diagnostic_auto_strategy': 'AUTO STRATEGY SELECTION',
            'diagnostic_testing': 'Testing:',
            'diagnostic_failed_to_start': 'Failed to start:',
            'diagnostic_started': 'Started',
            'diagnostic_result': 'Result:',
            'diagnostic_best_strategy': 'Best strategy:',
            'diagnostic_restoring_connection': 'Restoring connection...',
            'diagnostic_no_working_strategy': 'No working strategy found',
            'diagnostic_zapret_running': 'Zapret running',
            'diagnostic_zapret_not_running': 'Zapret not running',
            'diagnostic_searching_winws': 'Searching for winws.exe processes...',
            'diagnostic_started_at': 'started at:',
            'diagnostic_winws_not_found': 'winws.exe processes not found',
            'diagnostic_restarting_zapret': 'Restarting Zapret...',
            'diagnostic_checking_zapret': 'Checking Zapret status...',
            'diagnostic_zapret_restarted': 'Zapret restarted',
            'diagnostic_zapret_not_started': 'Zapret was not started',
            'diagnostic_checking_tgproxy': 'Checking TGProxy status...',
            'diagnostic_tgproxy_running': 'TGProxy running',
            'diagnostic_tgproxy_not_running': 'TGProxy not running',
            'diagnostic_restarting_tgproxy': 'Restarting TGProxy...',
            'diagnostic_tgproxy_restarted': 'TGProxy restarted',
            'diagnostic_tgproxy_not_started': 'TGProxy was not started',
            'diagnostic_opening_folder': 'Opening folder:',
            'diagnostic_full_diagnostic': 'FULL DIAGNOSTIC',
            'diagnostic_launcher_version': 'Launcher version:',
            'diagnostic_current_dns': 'Current DNS servers:',
            'diagnostic_complete': 'Diagnostic complete',
            'diagnostic_report_saved': 'Report saved:',
            'diagnostic_clearing_cache': 'Clearing cache...',
            'diagnostic_checking': 'Checking...',
            'diagnostic_available': 'AVAILABLE',
            'diagnostic_not_available': 'NOT AVAILABLE',
            'diagnostic_dns_error': 'DNS ERROR - site not found',
            'diagnostic_timeout': 'TIMEOUT - site not responding',
            'diagnostic_enter_url': 'Enter site URL:',
            'diagnostic_not_determined': 'not determined',
            'diagnostic_all_ok': 'All files OK',
            'diagnostic_file_integrity': 'FILE INTEGRITY CHECK',
            'diagnostic_check_site': 'Check site',
        }
    }
    
    def __init__(self):
        self._current_lang = 'Russian'
        self._config_file = CONFIG_FILE
        self.load_language()
    
    def load_language(self):
        try:
            if self._config_file.exists():
                with open(self._config_file, 'r', encoding='utf-8') as f:
                    data = json.load(f)
                    lang = data.get('language', 'Russian')
                    if lang in self.LANGUAGES:
                        self._current_lang = lang
        except:
            pass
    
    def save_language(self):
        try:
            data = {}
            if self._config_file.exists():
                with open(self._config_file, 'r', encoding='utf-8') as f:
                    data = json.load(f)
            
            data['language'] = self._current_lang
            
            self._config_file.parent.mkdir(parents=True, exist_ok=True)
            with open(self._config_file, 'w', encoding='utf-8') as f:
                json.dump(data, f, indent=2, ensure_ascii=False)
        except:
            pass
    
    def set_language(self, lang_code: str) -> bool:
        if lang_code in self.LANGUAGES:
            self._current_lang = lang_code
            self.save_language()
            return True
        return False
    
    def get_current_language(self) -> str:
        return self._current_lang
    
    def get_language_name(self) -> str:
        return self.LANGUAGES.get(self._current_lang, 'Russian')
    
    def get_available_languages(self) -> dict:
        return self.LANGUAGES.copy()
    
    def tr(self, key: str, **kwargs) -> str:
        text = self.TRANSLATIONS.get(self._current_lang, {}).get(key, key)
        
        if kwargs:
            for k, v in kwargs.items():
                text = text.replace(f'{{{k}}}', str(v))
        
        return text

_languages = None

def get_languages() -> Languages:
    global _languages
    if _languages is None:
        _languages = Languages()
    return _languages

def tr(key: str, **kwargs) -> str:
    return get_languages().tr(key, **kwargs)

def set_language(lang_code: str) -> bool:
    return get_languages().set_language(lang_code)

def get_current_language() -> str:
    return get_languages().get_current_language()

def get_available_languages() -> dict:
    return get_languages().get_available_languages()
